apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:6f651b53842ec4ff157def6f056a0ac2d8f5e499d5fe66a6b9a432427aa96161
  name: quay.io/red-wine-software/vote-api
  newName: quay.io/red-wine-software/vote-api
